version: 2.1

executors:
  main:
    working_directory: ~/app
    docker:
      - image: circleci/elixir:1.9.1-node
        environment:
          MIX_ENV: test
          NODE_ENV: test
          DATABASE_URL: "ecto://postgres:@0.0.0.0:5432/phoenix_starter_ci"
      - image: circleci/postgres:12.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: phoenix_starter_ci
          POSTGRES_PASSWORD: ""

commands:
  setup:
    steps:
      - checkout
      - run: mkdir -p tmp/downloads
      - run: chown -R $USER:$USER tmp
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}-{{ checksum "yarn.lock" }}
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
jobs:
  prepare:
    executor: main
    steps:
      - setup
      - run: MIX_ENV=test mix do deps.get, compile
      - run: yarn install
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - "deps"
            - "node_modules"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths:
            - "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths:
            - "_build"
            - "config"
      - save_cache:
          key: v1-build-cache
          paths:
            - "_build"
            - "config"
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    executor: main
    steps:
      - attach_workspace:
          at: .
      - setup
      - run: mix format --check-formatted
      - run: mix credo --strict
      - run: yarn lint
      - run: yarn lint-styles

  test:
    executor: main
    steps:
      - attach_workspace:
          at: .
      - setup
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix test

workflows:
  main:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
