name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_HOSTNAME: 0.0.0.0

    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: 1.11.4
        otp-version: 23.3

    - name: Cache elixir deps
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - name: Cache yarn deps
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache build
      uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Setup latest Chromedriver
      uses: nanasess/setup-chromedriver@master

    - name: Install Dependencies
      run: |
        sudo apt install inotify-tools
        mix deps.get
        yarn
        gem install foreman

    - name: Linting
      run: |
        mix format --check-formatted
        mix credo --strict
        yarn lint
        yarn lint-styles

    - name: Run Tests
      run: mix test

    - name: Run Server
      run: bin/server

    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.2.0
      with:
        target: '127.0.0.1:4000'

    - name: Test for public javascript library vulnerabilities
      uses: lirantal/is-website-vulnerable@master
      with:
        scan-url: '127.0.0.1:4000'

    - name: Dalfox scan
      uses: hahwul/action-dalfox@main
      id: xss-result
      with:
        target: '127.0.0.1:4000'
        mode: url
        cmd_options: '--follow-redirects'

    - name: Dalfox scan
      uses: hahwul/action-dalfox@main
      id: pipe-result
      with:
        target: 'https://finiam-phoenix-starter.herokuapp.com\nhttps://finiam-phoenix-starter.herokuapp.com/api/example\nhttps://finiam-phoenix-starter.herokuapp.com/api/user\nhttps://finiam-phoenix-starter.herokuapp.com/api/sessions\nhttps://finiam-phoenix-starter.herokuapp.com/admin/analytics '
        mode: pipe

    - name: Sobelow Action
      uses: sobelow/action@v1
      with:
        flags: '-i Config'
    - name: Report sobelow
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
